#!/usr/bin/env bash
#display time (hours and minutes)

hour=0

while [ $hour -le 12]
do

minute=1

while [ $minute -le 59 ]
do 
echo "$hour hour(s) and $minute minute(s)"

((minute++))
done

((hour++))
done
