#!/usr/bin/env bash
#i hate you

echo $$ > "/var/run/myscript.pid"
trap 'echo "Y U no love me?1"' SIGINT
trap '"echo "I hate the kil commmand"; rm -f /vat/run/myscript.pid; exit 0' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT
while true; do 
	echo "To infinity and beyond"
	sleep 1
done
