#!/usr/bin/env bash

# Create /var/run/myscript.pid containing its own PID
echo $$ > /var/run/myscript.pid

# Trap SIGINT
trap 'echo "Y U no love me?!"' SIGINT

# Trap SIGTERM
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM

# Trap SIGQUIT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

